Repository WildCodeSchool/2022-03-php-orleans-project-aoyos, pull requests merged in 2022-07, with the labels that each got.

#378 S04 us74 dj gps coords
  migrations/Version20220628105327.php
  src/Controller/DjController.php
  src/Entity/Artist.php
  src/Form/ArtistType.php
  src/Model/Localizable.php
  src/Service/DistanceCalculator.php
Labels: Reviewed, Conflicts solved

#397 fix_dj_sidebar
  templates/components/_dj_sidebar.html.twig
Labels: Reviewed, Fix

#398 fix seachbar validated
  src/Controller/AdminReservationController.php
  src/Repository/ReservationRepository.php
Labels: Reviewed, Fix

#399 S04 us75 reservation coordinates
  migrations/Version20220704075644.php
  src/Controller/ClientController.php
  src/Entity/Reservation.php
Labels: Reviewed

#406 S04 us78 admin index dj
  src/Controller/AdminController.php
  templates/admin/dj/index.html.twig
  templates/components/_admin_sidebar.html.twig
Labels: Reviewed

#407 Fix ck editor article
  assets/styles/home.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/fos_ckeditor.yaml
  src/Form/ArticleType.php
  symfony.lock
  templates/article/index.html.twig
  templates/components/_home_services.html.twig
Labels: Reviewed

#381 S04 us26 dj s events
  src/Controller/DjDashboardController.php
  src/Repository/ReservationRepository.php
  templates/components/_dj_sidebar.html.twig
  templates/dj_dashboard/_cards_dj.html.twig
  templates/dj_dashboard/my_events.html.twig
Labels: Reviewed, Conflicts solved

#408 S03 us77 reset password
  composer.json
  composer.lock
  config/bundles.php
  config/packages/reset_password.yaml
  migrations/Version20220704074150.php
  src/Controller/ResetPasswordController.php
  src/Entity/ResetPasswordRequest.php
  src/Form/ChangePasswordFormType.php
  src/Form/ResetPasswordRequestFormType.php
  src/Repository/ResetPasswordRequestRepository.php
  symfony.lock
  templates/login/index.html.twig
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
Labels: Reviewed, Conflicts solved

#411 fix dj profile
  src/Controller/DjProfileController.php
Labels: Reviewed, Fix

#412 admin dj link
  templates/admin/dj/index.html.twig
Labels: Reviewed, Fix

#415 S04 us83 social dj
  migrations/Version20220704135014.php
  src/Entity/Artist.php
  src/Form/ArtistProfileType.php
Labels: Reviewed

#429 Fix_DJ_Form_Style
  assets/styles/registration.scss
  templates/dj/registration/index.html.twig
Labels: Reviewed, Fix

#430 fix_admin_dj_show
  templates/admin/dj/show.html.twig
Labels: Reviewed, Fix

#427 S04US86_DJ_event_canceled
  src/Controller/DjDashboardController.php
  templates/dj_dashboard/_cards_dj.html.twig
  templates/dj_dashboard/notification_email_reservation_canceled.html.twig
  templates/dj_dashboard/reservation/_cancel_reservation.html.twig
  templates/dj_dashboard/reservation/show.html.twig
Labels: Reviewed

#416 S03 us82 admin reservation filtre status
  assets/searchStatusSubmit.js
  assets/styles/admin.scss
  src/Controller/AdminReservationController.php
  src/Form/SearchAdminReservationType.php
  src/Repository/ReservationRepository.php
  templates/admin/reservation/index.html.twig
  webpack.config.js
Labels: Reviewed, Conflicts solved

#428 S04US66_DJ_event_accepted
  src/Controller/DjDashboardController.php
  templates/dj_dashboard/_cards_dj.html.twig
  templates/dj_dashboard/notification_email_reservation_validated.html.twig
  templates/dj_dashboard/reservation/show.html.twig
Labels: Reviewed, Conflicts solved

#431 Fix_Admin_Reservation_Taken_Filter_status
  src/Controller/AdminReservationController.php
  templates/admin/reservation/index.html.twig
Labels: Reviewed, Fix

#434 Fix_Responsive_Form_Client
  templates/components/client/_form.html.twig
Labels: Reviewed, Fix

#437 fix dj dashboard
  src/Controller/DjDashboardController.php
Labels: Reviewed

#444 S04US88 admin deactivate dj
  src/Controller/AdminController.php
  templates/admin/dj/_dj_deactivate_form.html.twig
  templates/admin/dj/index.html.twig
Labels: Reviewed

#443 S04US87_Admin_Filter_Reservation_Company
  src/Form/SearchAdminReservationType.php
  src/Repository/ReservationRepository.php
Labels: Reviewed, Corrections done

#433 S04US24_DJ_offers_filtred
  src/Controller/DjDashboardController.php
  src/DataFixtures/ReservationFixtures.php
  src/Form/SearchDjReservationsType.php
  src/Repository/ReservationRepository.php
  templates/components/_dj_sidebar.html.twig
  templates/dj_dashboard/reservation/index.html.twig
Labels: Reviewed, Conflicts solved

#448 fix placeholder dj
  src/Form/ArtistProfileType.php
Labels: Reviewed, Fix

#449 Fix dj cards offres
  assets/styles/djDashboard.scss
  templates/dj_dashboard/reservation/show.html.twig
Labels: Review needed, Fix

#451 fix admin sidebar
  templates/components/_admin_sidebar.html.twig
Labels: Reviewed, Fix

#450 fix admin links index
  templates/admin/index.html.twig
Labels: Reviewed, Fix

#452 S04 us84 add djs to team
  assets/styles/team.scss
  src/Controller/TeamMemberController.php
  src/Entity/Artist.php
  src/Repository/UserRepository.php
  templates/team/index.html.twig
Labels: Reviewed

#445 Fix_Message_Flash_Admin_DJ
  templates/admin/admin_base.html.twig
  templates/base.html.twig
  templates/components/_flash_message.html.twig
  templates/dj_dashboard/dj_dashboard_base.html.twig
Labels: Reviewed, Fix

#453 Fix_Filter_Company_Reservation_Taken
  src/Repository/ReservationRepository.php
Labels: Reviewed, Fix

#455 fix_dashboard_index
  assets/styles/djDashboard.scss
  src/Controller/DjDashboardController.php
  templates/dj_dashboard/_cards_dj.html.twig
  templates/dj_dashboard/index.html.twig
  templates/dj_dashboard/reservation/_accept_reservation.html.twig
  templates/dj_dashboard/reservation/_cancel_reservation.html.twig
Labels: Reviewed, Fix

#466 S04US92 admin dj reservation count
  templates/admin/dj/index.html.twig
Labels: Reviewed

#467 Fix reservations status and views
  src/Controller/AdminReservationController.php
  src/Controller/DjDashboardController.php
  src/Repository/ReservationRepository.php
  templates/admin/reservation/index.html.twig
Labels: Reviewed, Fix

#468 fix - view dj not validated
  templates/dj_dashboard/index.html.twig
Labels: Reviewed, Fix

#461 S04 us28 dj bill
  assets/styles/djDashboard.scss
  config/packages/vich_uploader.yaml
  migrations/Version20220706134241.php
  public/uploads/images/bill/.gitignore
  src/Controller/DjDashboardController.php
  src/Entity/Reservation.php
  src/Form/ArtistBillType.php
  templates/dj_dashboard/my_events.html.twig
  templates/dj_dashboard/notification_email_new_bill.html.twig
  templates/dj_dashboard/reservation/show.html.twig
Labels: Reviewed, Conflicts solved

#470 S04US90 legal mentions
  src/Controller/HomeController.php
  templates/components/_footer.html.twig
  templates/home/legal_mentions.html.twig
Labels: Reviewed

#473 S04US91 general conditions
  src/Controller/HomeController.php
  templates/components/_footer.html.twig
  templates/home/general_conditions.html.twig
Labels: Reviewed, Conflicts solved

#476 fix - aoyos sans majuscule
  templates/dj_dashboard/index.html.twig
Labels: Reviewed, Fix

#484 S04US97 dj resa map
  templates/dj_dashboard/reservation/show.html.twig
Labels: Reviewed

#487 fix - éléments navbar admin
  templates/components/_admin_sidebar.html.twig
Labels: Reviewed, Fix

#488 fix home spacing
  templates/components/_banner_main.html.twig
  templates/components/_home_partners.html.twig
Labels: Reviewed, Fix

#489 S04 us93 dj avaibility add
  src/Controller/DjDashboardController.php
  src/Entity/Unavailability.php
  src/Form/UnavailabilityType.php
  templates/dj_dashboard/unavailability/_delete_form.html.twig
  templates/dj_dashboard/unavailability/_form.html.twig
  templates/dj_dashboard/unavailability/edit.html.twig
  templates/dj_dashboard/unavailability/index.html.twig
  templates/dj_dashboard/unavailability/new.html.twig
Labels: Reviewed

#490 fix access denied
  src/Controller/DjDashboardController.php
Labels: Reviewed, Fix

#492 fix distance offer
  src/Controller/DjDashboardController.php
Labels: Reviewed, Fix

#494 fix dj offers
  src/Controller/DjDashboardController.php
Labels: Reviewed, Fix

#495 S04US95 dj delete unavailability
  src/Controller/DjDashboardController.php
  templates/dj_dashboard/unavailability/index.html.twig
Labels: Reviewed, Fix

#491 fix - dj show reservation null fields
  templates/dj_dashboard/reservation/show.html.twig
Labels: Reviewed, Fix, Corrections done

#497 fix - redirect after accept/cancel booking
  src/Controller/DjDashboardController.php
Labels: Reviewed, Fix

#498 fix dj other offers
  templates/dj_dashboard/_cards_dj.html.twig
Labels: Reviewed, Fix

#499 fix - home djnewevents
  src/Controller/DjDashboardController.php
Labels: Reviewed, Fix

#500 everyday i dev to main
  src/Controller/AdminReservationController.php
  src/Controller/DjDashboardController.php
  src/Form/ReservationType.php
  templates/dj_dashboard/_cards_dj.html.twig
  templates/dj_dashboard/reservation/show.html.twig
  templates/dj_dashboard/unavailability/index.html.twig
Labels: Reviewed

#501 S04 us98 bills for admin
  assets/styles/admin.scss
  src/Controller/AdminReservationController.php
  templates/admin/reservation/billed.html.twig
  templates/components/_admin_sidebar.html.twig
Labels: Reviewed

#502 fix details dj
  templates/dj_dashboard/_cards_dj.html.twig
Labels: Reviewed, Fix

#503 fix - navbarspacingandqsn
  templates/components/_navbar.html.twig
Labels: Reviewed, Fix

#507 fix coords dj edit
  src/Controller/DjProfileController.php
Labels: Reviewed, Fix

#506 fix dj resa button
  templates/dj_dashboard/_cards_dj.html.twig
Labels: Reviewed, Fix

#509 S05 us99 djs unavailabilities admin
  src/Controller/AdminController.php
  templates/admin/dj/unavailability.html.twig
  templates/components/_admin_sidebar.html.twig
Labels: Reviewed

#508 Readme
  README.md
Labels: Reviewed, Corrections done

#510 fix - background team
  assets/styles/team.scss
  templates/team/index.html.twig
Labels: Reviewed, Fix

#512 fix-orga details reservation
  templates/dj_dashboard/reservation/show.html.twig
Labels: Reviewed, Fix

#518 fix social links
  templates/components/_footer.html.twig
Labels: Reviewed, Fix

#516 Fix team
  assets/styles/team.scss
  templates/team/index.html.twig
Labels: Reviewed, Fix, Corrections done

#522 Fix_admin_show_dj
  templates/admin/dj/show.html.twig
Labels: Reviewed, Fix

#525 fix dj form style
  assets/styles/registration.scss
  src/Form/ArtistProfileType.php
  templates/dj/registration/index.html.twig
Labels: Reviewed, Fix

#526 fix edit resa admin
  src/Controller/AdminReservationController.php
Labels: Reviewed, Fix

#527 Fix offers dj
  templates/dj_dashboard/_cards_dj.html.twig
  templates/dj_dashboard/reservation/index.html.twig
Labels: Reviewed, Fix

#519 fix - dj profile style
  assets/styles/djDashboard.scss
  src/Form/ArtistType.php
  templates/dj_dashboard/profile/edit.html.twig
Labels: Reviewed, Fix, Conflicts solved

#523 Fix - style indisponibilities
  assets/styles/djDashboard.scss
  templates/dj_dashboard/reservation/show.html.twig
  templates/dj_dashboard/unavailability/index.html.twig
Labels: Reviewed, Fix

#528 fix - myevents typo
  templates/dj_dashboard/my_events.html.twig
Labels: Reviewed, Fix

#529 fix forgotten curly braces
  assets/styles/djDashboard.scss
Labels: Reviewed, Fix

#535 fix link to keep open section
  templates/components/_admin_sidebar.html.twig
Labels: Reviewed, Fix

#532 fix home services
  templates/components/_home_services.html.twig
Labels: Reviewed, Fix

#531 fix home partners
  templates/components/_home_partners.html.twig
Labels: Reviewed, Fix

#534 fix dj empty resa
  templates/dj_dashboard/reservation/index.html.twig
Labels: Reviewed, Fix

#536 dev to main gotta go fast
  assets/styles/djDashboard.scss
  src/Controller/AdminReservationController.php
  src/Form/ArtistType.php
  templates/components/_admin_sidebar.html.twig
  templates/components/_home_partners.html.twig
  templates/components/_home_services.html.twig
  templates/dj_dashboard/_cards_dj.html.twig
  templates/dj_dashboard/my_events.html.twig
  templates/dj_dashboard/profile/edit.html.twig
  templates/dj_dashboard/reservation/index.html.twig
  templates/dj_dashboard/reservation/show.html.twig
  templates/dj_dashboard/unavailability/index.html.twig
  templates/team/index.html.twig
Labels: Reviewed

#530 Fix unavailability djs list
  templates/admin/dj/index.html.twig
Labels: Reviewed, Fix, Corrections done

#560 fix git ignore
  public/uploads/images/dj/.gitignore
Labels: Reviewed, Fix

#559 Fix responsive dj login
  assets/styles/dj.scss
  templates/login/index.html.twig
Labels: Reviewed, Fix

#563 fix services style
  templates/article/index.html.twig
Labels: Reviewed, Fix

#561 Fix - migrationmusicalstyle
  migrations/Version20220712092210.php
Labels: Reviewed, Fix

#562 fix - readme more details
  README.md
Labels: Reviewed, Fix

#564 fix - dj register email
  src/Form/ArtistType.php
Labels: Reviewed, Fix

#568 fix - team page
  assets/styles/team.scss
  templates/team/index.html.twig
Labels: Reviewed, Fix

#569 Fix dj space
  templates/dj_dashboard/my_events.html.twig
  templates/dj_dashboard/reservation/show.html.twig
Labels: Reviewed, Fix

#565 fix empty services
  assets/styles/article.scss
  templates/article/index.html.twig
  templates/components/_home_services.html.twig
Labels: Review needed, Fix, Conflicts solved

#570 fix dj form
  src/Controller/DjController.php
  src/Entity/Artist.php
  src/Form/ArtistProfileType.php
Labels: Reviewed, Fix

#571 fix admin member form
  src/Controller/ClientController.php
  src/Entity/Reservation.php
  src/Form/TeamMemberType.php
Labels: Reviewed, Fix

#572 fix admin dj list
  templates/admin/dj/index.html.twig
Labels: Reviewed, Fix

#573 fix dj form
  src/Controller/DjController.php
  src/Entity/Artist.php
Labels: Reviewed, Fix

#580 fix logo link
  templates/components/_admin_topBar.html.twig
  templates/components/_dj_sidebar.html.twig
  templates/components/_dj_topbar.html.twig
Labels: Reviewed, Fix

#579 add width and height to card
  assets/styles/home.scss
  templates/components/_home_services.html.twig
Labels: Reviewed, Fix, Conflicts solved

#610 Fix_Admin_Resa_Filter_Status
  src/Repository/ReservationRepository.php
  templates/admin/reservation/index.html.twig
Labels: Reviewed, Fix

#613 fix artist name dj list
  templates/admin/dj/index.html.twig
Labels: Reviewed, Fix

#614 Fix_Dj_new_events
  src/Controller/DjDashboardController.php
  templates/dj_dashboard/index.html.twig
Labels: Reviewed, Fix

#608 Fix card admin
  assets/styles/admin.scss
  templates/admin/_cards_admin_djs.html.twig
  templates/admin/_cards_admin_events.html.twig
  templates/admin/index.html.twig
Labels: Reviewed, Fix, Corrections done

#618 Fix contact mail
  templates/contact/new_email.html.twig
Labels: Reviewed, Fix

#617 Fix_admin_dj_show_return
  templates/admin/dj/show.html.twig
Labels: Reviewed, Fix

#619 fix - team role
  assets/styles/team.scss
  templates/team/index.html.twig
Labels: Reviewed, Fix

#621 Fix_admin_date_resa
  src/Entity/Reservation.php
Labels: Reviewed, Fix

#623 fix admin member
  src/Entity/TeamMember.php
Labels: Reviewed, Fix

#622 fix search taken resa
  src/Controller/AdminReservationController.php
  src/Repository/ReservationRepository.php
Labels: Reviewed, Fix

#624 fix nl2br
  src/Form/ArticleType.php
  src/Form/ProductionType.php
  templates/components/_home_production.html.twig
  templates/team/index.html.twig
Labels: Reviewed, Fix

#625 fix admin resa table
  templates/admin/reservation/index.html.twig
Labels: Reviewed, Fix

#626 Fix_admin_artistname_link
  assets/styles/admin.scss
  templates/admin/dj/index.html.twig
Labels: Reviewed, Fix

#627 Fix_icon_admin_card
  templates/admin/_cards_admin_djs.html.twig
  templates/admin/_cards_admin_events.html.twig
Labels: Reviewed, Fix

#629 Fix_admin_resa_edit
  src/Form/ReservationType.php
Labels: Reviewed, Fix

#630 Fix client reservation same page
  assets/controllers.json
  composer.json
  composer.lock
  package.json
  src/Controller/ClientController.php
  templates/base.html.twig
  templates/client/index.html.twig
  templates/components/_flash_message.html.twig
  templates/components/client/_form.html.twig
  templates/components/client/_header.html.twig
  yarn.lock
Labels: Reviewed, Fix

#635 fix responsive offers
  templates/dj_dashboard/_cards_dj.html.twig
Labels: Reviewed, Fix

#631 fix- cards team
  assets/styles/team.scss
  templates/team/index.html.twig
Labels: Reviewed, Fix

#636 Fix styledetailsdj
  assets/styles/admin.scss
  templates/admin/dj/show.html.twig
Labels: Reviewed, Fix

#637 fix_button_nav
  assets/styles/app.scss
  templates/components/_navbar.html.twig
Labels: Reviewed, Fix

#640 fix_reservation_admin_order
  src/Controller/AdminReservationController.php
Labels: Reviewed, Fix

#639 Fix add reservation admin
  src/Controller/AdminReservationController.php
  src/Form/ReservationType.php
  templates/admin/reservation/index.html.twig
  templates/admin/reservation/new.html.twig
  templates/components/_admin_sidebar.html.twig
Labels: Reviewed, Fix

#641 dev to main
  assets/controllers.json
  assets/styles/admin.scss
  assets/styles/app.scss
  assets/styles/team.scss
  composer.json
  composer.lock
  package.json
  src/Controller/AdminReservationController.php
  src/Controller/ClientController.php
  src/Controller/DjDashboardController.php
  src/Entity/Reservation.php
  src/Entity/TeamMember.php
  src/Form/ArticleType.php
  src/Form/ProductionType.php
  src/Form/ReservationType.php
  src/Repository/ReservationRepository.php
  templates/admin/_cards_admin_djs.html.twig
  templates/admin/_cards_admin_events.html.twig
  templates/admin/dj/index.html.twig
  templates/admin/dj/show.html.twig
  templates/admin/reservation/index.html.twig
  templates/admin/reservation/new.html.twig
  templates/base.html.twig
  templates/client/index.html.twig
  templates/components/_admin_sidebar.html.twig
  templates/components/_flash_message.html.twig
  templates/components/_home_production.html.twig
  templates/components/_navbar.html.twig
  templates/components/client/_form.html.twig
  templates/components/client/_header.html.twig
  templates/dj_dashboard/_cards_dj.html.twig
  templates/dj_dashboard/index.html.twig
  templates/dj_dashboard/reservation/index.html.twig
  templates/dj_dashboard/unavailability/index.html.twig
  templates/team/index.html.twig
  yarn.lock
Labels: Reviewed

#643 fix sidebars style
  assets/styles/app.scss
  templates/components/_admin_sidebar.html.twig
  templates/components/_dj_sidebar.html.twig
Labels: Reviewed, Fix

#644 Fix_Reservation_Entity
  src/Entity/Reservation.php
Labels: Reviewed, Fix

#645 Fix_Responsive_Margin_Dj_Form
  templates/dj/registration/index.html.twig
Labels: Reviewed, Fix

#646 Fix - artist name on invoice part
  templates/admin/reservation/billed.html.twig
Labels: Reviewed, Fix

#648 Fix mail admin dj
  src/Controller/AdminController.php
  src/Controller/DjProfileController.php
  src/Entity/Artist.php
  templates/admin/dj/_dj_deactivate_form.html.twig
  templates/admin/dj/_dj_validate_form.html.twig
  templates/admin/dj/dj_validated_email.html.twig
  templates/admin/dj/index.html.twig
  templates/dj/admin_completed_profile_email.html.twig
Labels: Reviewed, Fix

#651 fix horizontal scroll
  templates/login/index.html.twig
Labels: Reviewed, Fix

#650 add warning mail to dj
  src/Controller/AdminReservationController.php
  templates/admin/reservation/dj_event_modified_email.html.twig
Labels: Reviewed, Fix

#649 fix - team member picture required
  src/Form/TeamMemberType.php
Labels: Reviewed, Fix

#653 fix_findtaken_orderby_id
  src/Repository/ReservationRepository.php
Labels: Reviewed, Fix

#654 fix spacing edit team
  templates/admin/team_member/edit.html.twig
Labels: Reviewed, Fix

#655 it's the final dev to main TuDudUdUtuDuDu (normalement)
  assets/styles/app.scss
  src/Controller/AdminController.php
  src/Controller/AdminReservationController.php
  src/Controller/DjDashboardController.php
  src/Controller/DjProfileController.php
  src/Entity/Artist.php
  src/Entity/Reservation.php
  src/Form/TeamMemberType.php
  src/Repository/ReservationRepository.php
  templates/admin/dj/_dj_deactivate_form.html.twig
  templates/admin/dj/_dj_validate_form.html.twig
  templates/admin/dj/dj_validated_email.html.twig
  templates/admin/dj/index.html.twig
  templates/admin/reservation/billed.html.twig
  templates/admin/reservation/dj_event_modified_email.html.twig
  templates/admin/team_member/edit.html.twig
  templates/components/_admin_sidebar.html.twig
  templates/components/_dj_sidebar.html.twig
  templates/components/_home_partners.html.twig
  templates/dj/admin_completed_profile_email.html.twig
  templates/dj/registration/index.html.twig
  templates/dj_dashboard/index.html.twig
  templates/login/index.html.twig
Labels: Reviewed

#656 fix price resa index
  templates/dj_dashboard/_cards_dj.html.twig
Labels: Reviewed, Fix

#658 fix - events affichage
  src/Repository/ReservationRepository.php
Labels: Reviewed, Fix

#659 fix sidebar dj
  templates/components/_dj_sidebar.html.twig
Labels: Reviewed, Fix

#660 Fix_admin_name
  templates/components/_admin_topBar.html.twig
  templates/components/_dj_topbar.html.twig
Labels: Reviewed, Fix

#661 fix button dashboard
  templates/dj_dashboard/index.html.twig
Labels: Reviewed, Fix

#662 Fix_Admin_Link_Dashboard
  assets/styles/admin.scss
  assets/styles/app.scss
  templates/components/_admin_sidebar.html.twig
Labels: Reviewed, Fix

#663 fix responsive home
  templates/components/_home_production.html.twig
  templates/components/_home_services.html.twig
  templates/production/index.html.twig
Labels: Reviewed, Fix

#664 Fix_Dj_underline
  assets/styles/djDashboard.scss
  templates/components/_dj_sidebar.html.twig
Labels: Reviewed, Fix

#665 fix dashboard new event see more button
  templates/dj_dashboard/index.html.twig
Labels: Reviewed, Fix

#666 Fix_AOS_Productions
  templates/components/_home_production.html.twig
  templates/production/index.html.twig
Labels: Reviewed, Fix, Conflicts solved

#667 fix djdashboard order
  templates/dj_dashboard/index.html.twig
Labels: Reviewed, Fix, Conflicts solved

#657 Viser la dev to main ça n'me fait pas peur
  assets/styles/admin.scss
  assets/styles/app.scss
  assets/styles/djDashboard.scss
  src/Repository/ReservationRepository.php
  templates/components/_admin_sidebar.html.twig
  templates/components/_admin_topBar.html.twig
  templates/components/_dj_sidebar.html.twig
  templates/components/_dj_topbar.html.twig
  templates/components/_home_production.html.twig
  templates/components/_home_services.html.twig
  templates/dj_dashboard/_cards_dj.html.twig
  templates/dj_dashboard/index.html.twig
  templates/production/index.html.twig
Labels: Reviewed

#669 fix admin index
  templates/admin/index.html.twig
Labels: Reviewed, Fix

#670 fix sidebar icon size
  templates/components/_admin_sidebar.html.twig
Labels: Reviewed, Fix

#671 Je fais de toi ma dev to main, tu me fais naître parmi les devs
  templates/admin/index.html.twig
  templates/components/_admin_sidebar.html.twig
Labels: Reviewed

#672 fix of shame
  templates/dj_dashboard/index.html.twig
Labels: Reviewed, Fix
