Repository WildCodeSchool/2022-03-php-orleans-project-aoyos, pull requests merged in 2022-06, with the labels that each got.

#3 S0_Init_Bis
  assets/app.js
  assets/fonts/MazzardH-Bold.woff
  assets/fonts/MazzardH-Bold.woff2
  assets/styles/app.scss
  assets/styles/variables.scss
  config/packages/twig.yaml
  package.json
  templates/home/index.html.twig
  yarn.lock
Labels: Reviewed

#59 S01 us61 admin sidebar
  assets/images/logo.png
  assets/styles/admin.scss
  assets/styles/variables.scss
  src/Controller/AdminController.php
  templates/admin/admin_base.html.twig
  templates/admin/index.html.twig
  templates/base.html.twig
  templates/items/_admin_sidebar.html.twig
  webpack.config.js
Labels: Reviewed, Corrections done

#64 Fix colours
  assets/styles/variables.scss
Labels: Reviewed

#61 S01 us37 realisations show
  assets/styles/app.scss
  composer.json
  composer.lock
  migrations/Version20220608103039.php
  src/Controller/AdminProductionController.php
  src/DataFixtures/ProductionFixtures.php
  src/Entity/Production.php
  src/Form/ProductionType.php
  src/Repository/ProductionRepository.php
  symfony.lock
  templates/admin/production/_delete_form.html.twig
  templates/admin/production/_form.html.twig
  templates/admin/production/edit.html.twig
  templates/admin/production/index.html.twig
  templates/admin/production/new.html.twig
Labels: Reviewed, Corrections done

#66 Fix - fonts
  assets/styles/app.scss
  assets/styles/variables.scss
Labels: Reviewed

#69 S01US41 partner fix
  src/Controller/AdminPartnerController.php
  templates/admin/partner/index.html.twig
Labels: Reviewed, Corrections done

#71 Fix - font principale sur body
  assets/styles/app.scss
Labels: Reviewed

#70 S01US43 admin partner delete
  templates/admin/partner/_delete_form.html.twig
  templates/admin/partner/index.html.twig
Labels: Reviewed, Corrections done

#72 S01 us36 add production
  config/packages/translation.yaml
  src/Controller/AdminProductionController.php
  src/Entity/Production.php
  src/Form/ProductionType.php
  templates/admin/production/_form.html.twig
  templates/admin/production/new.html.twig
Labels: Reviewed, Corrections done

#76 Dev to main
  .github/workflows/main.yml
  assets/app.js
  assets/fonts/MazzardH-Bold.woff
  assets/fonts/MazzardH-Bold.woff2
  assets/images/aoyos-logo-dark.png
  assets/images/logo.png
  assets/styles/admin.scss
  assets/styles/app.scss
  assets/styles/variables.scss
  composer.json
  composer.lock
  config/packages/translation.yaml
  config/packages/twig.yaml
  migrations/Version20220608103039.php
  migrations/Version20220608125908.php
  migrations/Version20220608133623.php
  package.json
  src/Controller/AdminController.php
  src/Controller/AdminPartnerController.php
  src/Controller/AdminProductionController.php
  src/Controller/AdminTeamMemberController.php
  src/DataFixtures/PartnerFixtures.php
  src/DataFixtures/ProductionFixtures.php
  src/DataFixtures/TeamMemberFixtures.php
  src/Entity/Partner.php
  src/Entity/Production.php
  src/Entity/TeamMember.php
  src/Form/PartnerType.php
  src/Form/ProductionType.php
  src/Form/TeamMemberType.php
  src/Repository/PartnerRepository.php
  src/Repository/ProductionRepository.php
  src/Repository/TeamMemberRepository.php
  symfony.lock
  templates/admin/admin_base.html.twig
  templates/admin/index.html.twig
  templates/admin/partner/_delete_form.html.twig
  templates/admin/partner/_form.html.twig
  templates/admin/partner/edit.html.twig
  templates/admin/partner/index.html.twig
  templates/admin/partner/new.html.twig
  templates/admin/production/_delete_form.html.twig
  templates/admin/production/_form.html.twig
  templates/admin/production/edit.html.twig
  templates/admin/production/index.html.twig
  templates/admin/production/new.html.twig
  templates/admin_team_member/_delete_form.html.twig
  templates/admin_team_member/_form.html.twig
  templates/admin_team_member/edit.html.twig
  templates/admin_team_member/index.html.twig
  templates/admin_team_member/new.html.twig
  templates/admin_team_member/show.html.twig
  templates/base.html.twig
  templates/components/_navbar.html.twig
  templates/home/index.html.twig
  templates/items/_admin_sidebar.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed

#73 S01US40 admin partner add
  src/Controller/AdminPartnerController.php
  src/Entity/Partner.php
  src/Form/PartnerType.php
  templates/admin/partner/_form.html.twig
  templates/admin/partner/new.html.twig
Labels: Conflicts solved

#74 S01 us49 admin list services
  .env
  composer.json
  composer.lock
  migrations/Version20220608124133.php
  src/Controller/ArticleController.php
  src/DataFixtures/ArticleFixtures.php
  src/Entity/Article.php
  src/Form/ArticleType.php
  src/Repository/ArticleRepository.php
  symfony.lock
  templates/admin_article/_delete_form.html.twig
  templates/admin_article/_form.html.twig
  templates/admin_article/edit.html.twig
  templates/admin_article/index.html.twig
  templates/admin_article/new.html.twig
  templates/admin_article/show.html.twig
Labels: Reviewed

#77 Fix - boutons navbar
  templates/components/_navbar.html.twig
Labels: Reviewed, Fix

#78 Fix_Table_Messenger
  migrations/Version20220608124133.php
  migrations/Version20220608125908.php
  migrations/Version20220608133623.php
Labels: Reviewed, Fix

#79 S01US42 admin partner edit
  src/Controller/AdminPartnerController.php
  templates/admin/partner/edit.html.twig
Labels: Reviewed

#80 Fix_responsive_nav
  templates/components/_navbar.html.twig
Labels: Reviewed, Fix

#81 S01US38_EditProduction
  src/Controller/AdminProductionController.php
  templates/admin/production/edit.html.twig
Labels: Reviewed

#83 S01US48_Admin-add-services
  src/Controller/AdminArticleController.php
  src/Entity/Article.php
  src/Form/ArticleType.php
  templates/admin/article/_delete_form.html.twig
  templates/admin/article/_form.html.twig
  templates/admin/article/edit.html.twig
  templates/admin/article/index.html.twig
  templates/admin/article/new.html.twig
  templates/admin_article/_form.html.twig
  templates/admin_article/new.html.twig
  templates/admin_article/show.html.twig
Labels: Reviewed

#85 S01US02 footer
  assets/styles/app.scss
  templates/base.html.twig
  templates/components/_footer.html.twig
Labels: Reviewed

#75 S01 us3 banner
  assets/images/header-aoyos.jpeg
  assets/styles/home.scss
  assets/styles/variables.scss
  assets/typeAnimation.js
  templates/components/_banner_main.html.twig
  templates/home/index.html.twig
  webpack.config.js
Labels: Reviewed, Conflicts solved

#88 fix home js
  templates/home/index.html.twig
Labels: Reviewed

#84 S01 us44 team member add
  src/Controller/AdminTeamMemberController.php
  src/Entity/TeamMember.php
  src/Form/TeamMemberType.php
  templates/admin_team_member/_form.html.twig
  templates/admin_team_member/index.html.twig
  templates/admin_team_member/new.html.twig
Labels: Reviewed, Corrections done

#89 fix footer
  templates/components/_footer.html.twig
Labels: Reviewed, Corrections done

#139 S02 us06 home presentation
  assets/images/title_underline_blue.png
  assets/images/title_underline_orange.png
  assets/images/title_underline_pink.png
  assets/images/title_underline_purple.png
  assets/styles/app.scss
  assets/styles/home.scss
  assets/styles/variables.scss
  templates/base.html.twig
  templates/components/_home_presentation.html.twig
  templates/home/index.html.twig
Labels: Reviewed, Corrections done

#140 Fix admin team members
  src/Controller/AdminTeamMemberController.php
Labels: Reviewed

#142 S02 us11 client page
  assets/styles/client.scss
  src/Controller/ClientController.php
  templates/client/index.html.twig
  templates/components/client/_header.html.twig
  webpack.config.js
Labels: Reviewed

#145 S02US47-teamMemberDelete
  templates/admin_team_member/_delete_form.html.twig
  templates/admin_team_member/index.html.twig
Labels: Reviewed, Corrections done

#146 S02 us5 view partners
  assets/styles/home.scss
  src/Controller/HomeController.php
  templates/home/_partners.html.twig
  templates/home/index.html.twig
Labels: Review needed, Conflicts solved

#148 fix admin tab names
  templates/admin/admin_base.html.twig
Labels: Reviewed, Fix

#150 fix admin team directories
  src/Controller/AdminTeamMemberController.php
  templates/admin/team_member/_delete_form.html.twig
  templates/admin/team_member/_form.html.twig
  templates/admin/team_member/edit.html.twig
  templates/admin/team_member/index.html.twig
  templates/admin/team_member/new.html.twig
  templates/admin/team_member/show.html.twig
Labels: Reviewed, Fix

#151 fix admin layout
  templates/admin/article/edit.html.twig
  templates/admin/article/index.html.twig
  templates/admin/article/new.html.twig
Labels: Reviewed, Fix

#137 S02 us50 admin edit services
  src/Controller/AdminArticleController.php
  src/DataFixtures/ArticleFixtures.php
  src/Entity/Article.php
  templates/admin/article/_form.html.twig
  templates/admin/article/edit.html.twig
Labels: Reviewed, Corrections done

#153 Fix nav font
  assets/styles/app.scss
  assets/styles/variables.scss
Labels: Reviewed, Fix

#156 fix crud image size team
  assets/styles/admin.scss
  assets/styles/variables.scss
  templates/admin/partner/index.html.twig
Labels: Reviewed, Fix

#157 Fix_Logo_Partenaires
  assets/styles/home.scss
  templates/home/_partners.html.twig
Labels: Reviewed, Fix

#158 S02US39_ProductionDelete
  templates/admin/production/_delete_form.html.twig
Labels: Reviewed

#159 Dev to Main
  assets/images/placeholder-services.jpg
  assets/images/title_underline_blue.png
  assets/images/title_underline_orange.png
  assets/images/title_underline_pink.png
  assets/images/title_underline_purple.png
  assets/styles/admin.scss
  assets/styles/app.scss
  assets/styles/client.scss
  assets/styles/home.scss
  assets/styles/variables.scss
  src/Controller/AdminArticleController.php
  src/Controller/AdminTeamMemberController.php
  src/Controller/ClientController.php
  src/Controller/HomeController.php
  src/DataFixtures/ArticleFixtures.php
  src/DataFixtures/PartnerFixtures.php
  src/Entity/Article.php
  src/Entity/TeamMember.php
  src/Form/TeamMemberType.php
  templates/admin/admin_base.html.twig
  templates/admin/article/_delete_form.html.twig
  templates/admin/article/_form.html.twig
  templates/admin/article/edit.html.twig
  templates/admin/article/index.html.twig
  templates/admin/article/new.html.twig
  templates/admin/partner/index.html.twig
  templates/admin/production/_delete_form.html.twig
  templates/admin/team_member/_delete_form.html.twig
  templates/admin/team_member/_form.html.twig
  templates/admin/team_member/edit.html.twig
  templates/admin/team_member/index.html.twig
  templates/admin/team_member/new.html.twig
  templates/admin/team_member/show.html.twig
  templates/admin_team_member/_delete_form.html.twig
  templates/admin_team_member/_form.html.twig
  templates/admin_team_member/edit.html.twig
  templates/admin_team_member/new.html.twig
  templates/base.html.twig
  templates/client/index.html.twig
  templates/components/_banner_main.html.twig
  templates/components/_footer.html.twig
  templates/components/_home_presentation.html.twig
  templates/components/client/_header.html.twig
  templates/home/_partners.html.twig
  templates/home/_services.html.twig
  templates/home/index.html.twig
  webpack.config.js
Labels: Reviewed

#135 Fix sidebar placement
  assets/adminSidebar.js
  assets/styles/admin.scss
  assets/styles/variables.scss
  templates/admin/admin_base.html.twig
  templates/admin/article/index.html.twig
  templates/admin/article/new.html.twig
  templates/admin/partner/edit.html.twig
  templates/admin/partner/index.html.twig
  templates/admin/partner/new.html.twig
  templates/admin/production/edit.html.twig
  templates/admin/production/index.html.twig
  templates/admin/production/new.html.twig
  templates/admin/team_member/index.html.twig
  templates/base.html.twig
  templates/components/_admin_sidebar.html.twig
  templates/components/_admin_topBar.html.twig
  webpack.config.js
Labels: Reviewed, Conflicts solved

#154 Fix Nav Hover
  assets/styles/app.scss
  templates/components/_navbar.html.twig
Labels: Reviewed, Fix

#160 Fix_Again_Placement_partner
  assets/styles/home.scss
  templates/home/_partners.html.twig
Labels: Reviewed, Fix

#161 S02 us12 client commercial
  assets/images/price-underline.svg
  assets/styles/client.scss
  templates/client/index.html.twig
  templates/components/client/_sales_proposal.html.twig
Labels: Reviewed

#163 Fix btn admin
  templates/admin/article/_delete_form.html.twig
  templates/admin/article/_form.html.twig
  templates/admin/article/edit.html.twig
  templates/admin/article/index.html.twig
  templates/admin/article/new.html.twig
  templates/admin/partner/_delete_form.html.twig
  templates/admin/partner/_form.html.twig
  templates/admin/partner/edit.html.twig
  templates/admin/partner/index.html.twig
  templates/admin/partner/new.html.twig
  templates/admin/production/_delete_form.html.twig
  templates/admin/production/_form.html.twig
  templates/admin/production/edit.html.twig
  templates/admin/production/index.html.twig
  templates/admin/production/new.html.twig
  templates/admin/team_member/_delete_form.html.twig
  templates/admin/team_member/_form.html.twig
  templates/admin/team_member/edit.html.twig
  templates/admin/team_member/index.html.twig
  templates/admin/team_member/new.html.twig
Labels: Reviewed, Fix

#164 S02 us07 team
  assets/styles/team.scss
  assets/styles/variables.scss
  src/Controller/TeamMemberController.php
  templates/team/index.html.twig
  webpack.config.js
Labels: Reviewed, Conflicts solved

#165 S02US16-DjHome
  assets/images/dots.svg
  assets/styles/dj.scss
  src/Controller/DjController.php
  templates/dj/_banner_dj.html.twig
  templates/dj/index.html.twig
  webpack.config.js
Labels: Reviewed

#167 Dev To Main
  assets/adminSidebar.js
  assets/images/bg_production.svg
  assets/images/dots.svg
  assets/images/price-underline.svg
  assets/styles/admin.scss
  assets/styles/app.scss
  assets/styles/client.scss
  assets/styles/dj.scss
  assets/styles/home.scss
  assets/styles/team.scss
  assets/styles/variables.scss
  src/Controller/DjController.php
  src/Controller/HomeController.php
  src/Controller/TeamMemberController.php
  src/DataFixtures/ProductionFixtures.php
  templates/admin/admin_base.html.twig
  templates/admin/article/_delete_form.html.twig
  templates/admin/article/_form.html.twig
  templates/admin/article/edit.html.twig
  templates/admin/article/index.html.twig
  templates/admin/article/new.html.twig
  templates/admin/partner/_delete_form.html.twig
  templates/admin/partner/_form.html.twig
  templates/admin/partner/edit.html.twig
  templates/admin/partner/index.html.twig
  templates/admin/partner/new.html.twig
  templates/admin/production/_delete_form.html.twig
  templates/admin/production/_form.html.twig
  templates/admin/production/edit.html.twig
  templates/admin/production/index.html.twig
  templates/admin/production/new.html.twig
  templates/admin/team_member/_delete_form.html.twig
  templates/admin/team_member/_form.html.twig
  templates/admin/team_member/edit.html.twig
  templates/admin/team_member/index.html.twig
  templates/admin/team_member/new.html.twig
  templates/base.html.twig
  templates/client/index.html.twig
  templates/components/_admin_sidebar.html.twig
  templates/components/_admin_topBar.html.twig
  templates/components/_navbar.html.twig
  templates/components/_production_main.html.twig
  templates/components/client/_sales_proposal.html.twig
  templates/dj/_banner_dj.html.twig
  templates/dj/index.html.twig
  templates/home/_partners.html.twig
  templates/home/index.html.twig
  templates/team/index.html.twig
  webpack.config.js
Labels: Reviewed

#173 Fix - navbar côté client
  assets/styles/app.scss
  templates/components/_navbar.html.twig
Labels: Reviewed

#166 Fix upload image article
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  migrations/Version20220614144030.php
  src/DataFixtures/ArticleFixtures.php
  src/Entity/Article.php
  src/Form/ArticleType.php
  symfony.lock
Labels: Reviewed, Corrections done

#181 Fix home harmonization
  assets/images/bg_production.svg
  assets/styles/home.scss
  templates/components/_home_partners.html.twig
  templates/components/_home_presentation.html.twig
  templates/components/_home_services.html.twig
  templates/components/_production_main.html.twig
  templates/home/index.html.twig
Labels: Reviewed, Fix

#182 Fix_footer_animation
  templates/components/_footer.html.twig
Labels: Reviewed, Fix

#184 Fix_teamPage_h1underlined
  assets/styles/team.scss
  templates/team/index.html.twig
Labels: Reviewed, Fix

#185 Fix_ClientPage
  assets/styles/client.scss
  templates/components/client/_header.html.twig
Labels: Reviewed, Fix

#186 fix upload folder gitignore
  public/uploads/images/article/.gitignore
  src/Entity/.gitignore
Labels: Reviewed, Fix

#195 Fix admin
  src/Controller/AdminArticleController.php
  src/Controller/AdminProductionController.php
  templates/admin/article/index.html.twig
  templates/admin/partner/_form.html.twig
  templates/admin/production/edit.html.twig
  templates/admin/team_member/edit.html.twig
  templates/admin/team_member/new.html.twig
  templates/components/_admin_sidebar.html.twig
  templates/components/_admin_topBar.html.twig
Labels: Reviewed, Fix

#203 Fix - liens navbar
  templates/components/_home_presentation.html.twig
  templates/components/_home_services.html.twig
  templates/components/_navbar.html.twig
  templates/components/_production_main.html.twig
Labels: Reviewed, Fix

#183 S02 us14 reservation form client infos
  migrations/Version20220615120123.php
  src/Controller/ClientController.php
  src/Entity/Reservation.php
  src/Form/ReservationClientInfosType.php
  src/Repository/ReservationRepository.php
  templates/client/index.html.twig
  templates/components/client/_form.html.twig
  templates/components/client/_header.html.twig
  templates/components/client/_sales_proposal.html.twig
Labels: Reviewed, Conflicts solved

#196 S02 us52 admin musical style
  migrations/Version20220615131447.php
  src/Controller/AdminMusicalStyleController.php
  src/DataFixtures/MusicalStyleFixtures.php
  src/Entity/MusicalStyle.php
  src/Form/MusicalStyleType.php
  src/Repository/MusicalStyleRepository.php
  templates/admin/musical_style/_delete_form.html.twig
  templates/admin/musical_style/_form.html.twig
  templates/admin/musical_style/edit.html.twig
  templates/admin/musical_style/index.html.twig
  templates/admin/musical_style/new.html.twig
  templates/components/_admin_sidebar.html.twig
Labels: Reviewed, Corrections done

#205 Fix - dots image sur page dj
  assets/images/dots.png
  assets/images/dots.svg
  assets/styles/dj.scss
Labels: Reviewed

#201 S02 us30 login admin
  assets/styles/login.scss
  config/packages/security.yaml
  config/routes.yaml
  migrations/Version20220615101012.php
  src/Controller/LoginController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  templates/components/_admin_sidebar.html.twig
  templates/components/_footer.html.twig
  templates/login/index.html.twig
  webpack.config.js
Labels: Reviewed, Corrections done

#209 Fix_Ignore_Upload_Article
  public/uploads/images/article/.gitignore
Labels: Reviewed, Fix

#210 Fix_Fragment_Home
  assets/styles/app.scss
  assets/styles/variables.scss
  templates/components/_home_presentation.html.twig
  templates/components/_home_production.html.twig
  templates/components/_home_services.html.twig
  templates/home/index.html.twig
Labels: Reviewed, Fix

#213 Fix - Lien équipe QSN
  templates/components/_home_presentation.html.twig
Labels: Reviewed, Fix, Corrections done

#215 S02US55-DeleteMusicCat
  templates/admin/musical_style/_delete_form.html.twig
  templates/admin/musical_style/index.html.twig
Labels: Reviewed

#214 S02 us54 edit cat music
  src/Entity/MusicalStyle.php
  src/Form/MusicalStyleType.php
  templates/admin/musical_style/_form.html.twig
  templates/admin/musical_style/edit.html.twig
  templates/admin/musical_style/index.html.twig
Labels: Reviewed, Corrections done

#208 S02 us14 reservation form event infos
  migrations/Version20220616075550.php
  src/Controller/ClientController.php
  src/Entity/Reservation.php
  src/Form/ReservationEventInfosType.php
  templates/client/index.html.twig
  templates/components/client/_form.html.twig
Labels: Reviewed, Conflicts solved

#217 S02 us15 contact form
  assets/images/contact-texture.svg
  assets/styles/contact.scss
  config/packages/mailer.yaml
  config/services.yaml
  src/Controller/ContactController.php
  src/Form/ContactType.php
  templates/base.html.twig
  templates/components/_footer.html.twig
  templates/contact/index.html.twig
  templates/contact/new_email.html.twig
  templates/layout_email.html.twig
  webpack.config.js
Labels: Reviewed, Corrections done

#219 Dev to main du jeudi soir parce qu'on est de bons élèves
  assets/images/contact-texture.svg
  assets/images/dots.png
  assets/images/dots.svg
  assets/styles/admin.scss
  assets/styles/app.scss
  assets/styles/client.scss
  assets/styles/contact.scss
  assets/styles/dj.scss
  assets/styles/login.scss
  assets/styles/variables.scss
  config/packages/mailer.yaml
  config/packages/security.yaml
  config/routes.yaml
  config/services.yaml
  migrations/Version20220615101012.php
  migrations/Version20220616075550.php
  migrations/Version20220616133925.php
  public/uploads/images/article/.gitignore
  src/Controller/AdminController.php
  src/Controller/ClientController.php
  src/Controller/ContactController.php
  src/Controller/DjController.php
  src/Controller/DjRegistrationController.php
  src/Controller/LoginController.php
  src/DataFixtures/ArtistFixtures.php
  src/DataFixtures/ReservationFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Artist.php
  src/Entity/MusicalStyle.php
  src/Entity/Reservation.php
  src/Entity/User.php
  src/Form/ArtistProfileType.php
  src/Form/ContactType.php
  src/Form/MusicalStyleType.php
  src/Form/ReservationEventInfosType.php
  src/Repository/UserRepository.php
  templates/admin/index.html.twig
  templates/admin/musical_style/_delete_form.html.twig
  templates/admin/musical_style/_form.html.twig
  templates/admin/musical_style/edit.html.twig
  templates/admin/musical_style/index.html.twig
  templates/base.html.twig
  templates/client/index.html.twig
  templates/components/_admin_sidebar.html.twig
  templates/components/_footer.html.twig
  templates/components/_home_presentation.html.twig
  templates/components/_home_production.html.twig
  templates/components/_home_services.html.twig
  templates/components/_navbar.html.twig
  templates/components/client/_form.html.twig
  templates/components/client/_header.html.twig
  templates/contact/index.html.twig
  templates/contact/new_email.html.twig
  templates/dj/_banner_dj.html.twig
  templates/dj/registration/index.html.twig
  templates/home/index.html.twig
  templates/layout_email.html.twig
  templates/login/index.html.twig
  webpack.config.js
Labels: Reviewed

#222 Fix - Fixtures Dj
  src/DataFixtures/ArtistFixtures.php
  src/DataFixtures/MusicalStyleFixtures.php
Labels: Reviewed, Fix, Corrections done

#223 Fix_Fixtures_Reservation
  src/DataFixtures/ReservationFixtures.php
Labels: Reviewed, Fix, Corrections done

#224 Dev to main
  src/DataFixtures/ArtistFixtures.php
  src/DataFixtures/MusicalStyleFixtures.php
  src/DataFixtures/ReservationFixtures.php
Labels: Reviewed

#231 Fix_Form_Reservation_Step
  src/Controller/ClientController.php
Labels: Reviewed, Fix

#232 Fix_Spelling_DJ
  templates/dj/_banner_dj.html.twig
Labels: Reviewed, Fix

#226 Fix - style login
  assets/styles/login.scss
  templates/login/index.html.twig
Labels: Reviewed, Fix, Corrections done

#284 fix to standardize design
  assets/styles/home.scss
  templates/components/_home_services.html.twig
Labels: Reviewed, Fix

#289 Fix_Contactform_design
  assets/images/contact-texture.svg
  assets/styles/contact.scss
Labels: Reviewed

#288 Fix carouselhome
  assets/images/header-aoyos.jpeg
  assets/images/header1.jpeg
  assets/images/header2.jpeg
  assets/images/header3.jpeg
  assets/styles/home.scss
  templates/components/_banner_main.html.twig
Labels: Reviewed, Conflicts solved

#290 Fix contactform link
  assets/styles/app.scss
  templates/components/_footer.html.twig
Labels: Reviewed, Fix

#292 S03 us35 mail reservation admin
  src/Controller/ClientController.php
  templates/client/notification_email_reservation.html.twig
Labels: Reviewed

#293 Fix_btn_admin
  templates/admin/article/_delete_form.html.twig
  templates/admin/article/_form.html.twig
  templates/admin/article/edit.html.twig
  templates/admin/article/index.html.twig
  templates/admin/article/new.html.twig
  templates/admin/musical_style/_delete_form.html.twig
  templates/admin/musical_style/_form.html.twig
  templates/admin/musical_style/edit.html.twig
  templates/admin/musical_style/index.html.twig
  templates/admin/musical_style/new.html.twig
  templates/admin/partner/_delete_form.html.twig
  templates/admin/partner/_form.html.twig
  templates/admin/partner/edit.html.twig
  templates/admin/partner/index.html.twig
  templates/admin/partner/new.html.twig
  templates/admin/production/_delete_form.html.twig
  templates/admin/production/_form.html.twig
  templates/admin/production/edit.html.twig
  templates/admin/production/index.html.twig
  templates/admin/production/new.html.twig
  templates/admin/team_member/_delete_form.html.twig
  templates/admin/team_member/_form.html.twig
  templates/admin/team_member/edit.html.twig
  templates/admin/team_member/index.html.twig
  templates/admin/team_member/new.html.twig
Labels: Reviewed, Fix

#294 Fix_Client_Home_Call_To_Action
  templates/components/client/_header.html.twig
  templates/components/client/_sales_proposal.html.twig
Labels: Reviewed, Review needed, Fix

#291 Fix - fontsize home
  assets/styles/home.scss
Labels: Reviewed, Conflicts solved

#286 Fix_Admin_Sidebar_accordeon_section_open
  templates/base.html.twig
  templates/components/_admin_sidebar.html.twig
Labels: Reviewed, Fix

#295 Fix_Nav_Revert_Buttons_responsive
  assets/styles/app.scss
  assets/styles/variables.scss
  templates/components/_navbar.html.twig
Labels: Reviewed, Fix

#300 Fix - greyscale logos
  assets/styles/home.scss
Labels: Reviewed, Fix

#301 fix-QSNfontsize
  templates/components/_home_presentation.html.twig
Labels: Reviewed, Fix

#302 fix-teamcard
  templates/team/index.html.twig
Labels: Reviewed, Fix

#305 Fix reservation client validation date
  src/Entity/Reservation.php
Labels: Reviewed, Fix

#308 Fix_Client_Header_BG_Better_Quality
  assets/images/bg-client.jpg
  assets/images/bg_client.webp
  assets/styles/client.scss
Labels: Reviewed, Fix

#310 Fix adminhomecards
  assets/styles/admin.scss
  src/Controller/AdminController.php
  templates/admin/index.html.twig
Labels: Reviewed, Fix

#311 S03 us25 dj profile page
  src/Controller/DjProfileController.php
  src/Form/ArtistEditType.php
  src/Form/ArtistProfileType.php
  src/Form/ArtistType.php
  templates/dashboard-dj/dashboard_dj_base.html.twig
  templates/dashboard-dj/profile/edit.html.twig
Labels: Reviewed, Corrections done

#312 S03 us67 dashboard dj nav
  assets/styles/djDashboard.scss
  templates/components/_dj_sidebar.html.twig
  templates/components/_dj_topbar.html.twig
  webpack.config.js
Labels: Reviewed, Conflicts solved

#313 Fix - Titres réalisations
  templates/components/_home_production.html.twig
Labels: Reviewed, Fix

#314 Fix - route admin controller
  src/Controller/AdminController.php
  src/Controller/LoginController.php
Labels: Reviewed, Fix

#316 Fix crudadmin
  assets/styles/variables.scss
  src/Controller/TeamMemberController.php
  templates/admin/article/index.html.twig
  templates/admin/partner/index.html.twig
  templates/admin/production/index.html.twig
  templates/admin/team_member/index.html.twig
  templates/admin/team_member/show.html.twig
Labels: Reviewed, Fix

#315 Fix_connection_by_mail
  config/packages/security.yaml
  templates/login/index.html.twig
Labels: Reviewed, Fix

#320 Fix -navbar dj sur base
  assets/sidebar.js
  assets/styles/djDashboard.scss
  templates/admin/admin_base.html.twig
  templates/dj_dashboard/dj_dashboard_base.html.twig
  webpack.config.js
Labels: Reviewed, Fix

#323 S03 us19 dj form won
  migrations/Version20220623102835.php
  src/Controller/DjController.php
  src/Entity/Artist.php
  src/Entity/User.php
  src/Form/ArtistProfileType.php
  src/Form/ArtistRegistrationType.php
  src/Form/ArtistType.php
  templates/dj/registration/index.html.twig
Labels: Reviewed

#322 Fix_Client_Reservation_Button_Back
  templates/components/client/_form.html.twig
Labels: Reviewed, Fix

#327 fix just a clamp
  assets/styles/home.scss
Labels: Reviewed, Fix

#319 Fix add upload to team prod partner
  config/packages/vich_uploader.yaml
  migrations/Version20220622185635.php
  src/DataFixtures/PartnerFixtures.php
  src/DataFixtures/ProductionFixtures.php
  src/DataFixtures/TeamMemberFixtures.php
  src/Entity/Partner.php
  src/Entity/Production.php
  src/Entity/TeamMember.php
  src/Form/PartnerType.php
  src/Form/ProductionType.php
  src/Form/TeamMemberType.php
  templates/admin/partner/index.html.twig
  templates/components/_home_partners.html.twig
  templates/components/_home_production.html.twig
  templates/team/index.html.twig
Labels: Reviewed, Conflicts solved

#321 Fix_Admin_Link_Footer
  templates/components/_footer.html.twig
Labels: Reviewed, Fix, Corrections done

#330 S03 us33 admin edit reservation
  src/Form/ReservationType.php
  templates/admin/reservation/_form.html.twig
  templates/admin/reservation/edit.html.twig
Labels: Reviewed

#331 Programmeur vers Digital
  assets/styles/home.scss
  config/packages/vich_uploader.yaml
  migrations/Version20220622185635.php
  migrations/Version20220623102835.php
  src/Controller/DjController.php
  src/DataFixtures/PartnerFixtures.php
  src/DataFixtures/ProductionFixtures.php
  src/DataFixtures/TeamMemberFixtures.php
  src/Entity/Artist.php
  src/Entity/Partner.php
  src/Entity/Production.php
  src/Entity/TeamMember.php
  src/Entity/User.php
  src/Form/ArtistProfileType.php
  src/Form/ArtistRegistrationType.php
  src/Form/ArtistType.php
  src/Form/PartnerType.php
  src/Form/ProductionType.php
  src/Form/ReservationType.php
  src/Form/TeamMemberType.php
  templates/admin/partner/index.html.twig
  templates/admin/reservation/_form.html.twig
  templates/admin/reservation/edit.html.twig
  templates/components/_footer.html.twig
  templates/components/_home_partners.html.twig
  templates/components/_home_production.html.twig
  templates/components/client/_form.html.twig
  templates/dj/registration/index.html.twig
  templates/team/index.html.twig
Labels: Reviewed

#332 Fix_dj_dashboard_files
  src/Controller/DjProfileController.php
  templates/dashboard-dj/dashboard_dj_base.html.twig
  templates/dj_dashboard/profile/edit.html.twig
Labels: Reviewed, Fix

#328 S03 us23 accepteddjindex
  assets/styles/djDashboard.scss
  config/packages/security.yaml
  migrations/Version20220623094554.php
  migrations/Version20220624104018.php
  src/Controller/DjDashboardController.php
  src/DataFixtures/ArtistFixtures.php
  src/DataFixtures/ReservationFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Artist.php
  src/Entity/Reservation.php
  src/Entity/User.php
  templates/dj_dashboard/index.html.twig
Labels: Reviewed, Conflicts solved

#339 fix artist user form
  src/Controller/DjController.php
  src/Entity/Artist.php
Labels: Reviewed, Fix

#341 Fix_profile_Dj
  src/Form/ArtistEditType.php
  templates/base.html.twig
  templates/components/_dj_sidebar.html.twig
  templates/dj_dashboard/profile/edit.html.twig
Labels: Reviewed, Fix

#343 Dev2Main
  Dockerfile
  src/Controller/DjController.php
  src/Entity/Artist.php
  src/Form/ArtistEditType.php
  templates/base.html.twig
  templates/components/_dj_sidebar.html.twig
  templates/dj_dashboard/profile/edit.html.twig
Labels: Reviewed

#344 S04US62_Admin_Reservation_Delete
  templates/admin/reservation/_delete_form.html.twig
Labels: Reviewed

#345 Fix_Admin_Reservation_Show_Displayed
  templates/admin/reservation/index.html.twig
Labels: Reviewed, Fix

#351 Fix - background login
  assets/images/dotsagain.png
  assets/styles/login.scss
  templates/login/index.html.twig
Labels: Reviewed, Fix

#352 S04 us64 admin reservation add price
  migrations/Version20220627085649.php
  src/Entity/Reservation.php
  src/Form/ReservationType.php
  templates/admin/reservation/index.html.twig
Labels: Reviewed

#350 Fix design bg
  assets/images/cloud_lines.png
  assets/images/gradient_lines.png
  assets/images/splash-paint.png
  assets/styles/article.scss
  assets/styles/contact.scss
  assets/styles/home.scss
  templates/article/index.html.twig
  templates/contact/index.html.twig
Labels: Reviewed, Fix

#357 S04US70 reservation musical styles
  migrations/Version20220627111257.php
  src/Entity/MusicalStyle.php
  src/Entity/Reservation.php
  src/Form/ReservationType.php
Labels: Reviewed

#363 S04 us71 taken reservations
  src/Controller/AdminReservationController.php
  src/Repository/ReservationRepository.php
  templates/components/_admin_sidebar.html.twig
Labels: Reviewed

#374 Fix_Admin_Sidebar_Accordeon
  templates/components/_admin_sidebar.html.twig
Labels: Reviewed, Fix

#370 S04 us72 admin reservation comment
  migrations/Version20220627133735.php
  src/DataFixtures/ReservationFixtures.php
  src/Entity/Reservation.php
  src/Form/ReservationEventInfosType.php
  src/Form/ReservationType.php
Labels: Reviewed

#379 Dave2Men
  assets/images/cloud_lines.png
  assets/images/dotsagain.png
  assets/images/gradient_lines.png
  assets/images/splash-paint.png
  assets/styles/article.scss
  assets/styles/contact.scss
  assets/styles/djDashboard.scss
  assets/styles/home.scss
  assets/styles/login.scss
  migrations/Version20220627085649.php
  migrations/Version20220627111257.php
  migrations/Version20220627133735.php
  src/Controller/AdminReservationController.php
  src/DataFixtures/ReservationFixtures.php
  src/Entity/MusicalStyle.php
  src/Entity/Reservation.php
  src/Form/ReservationEventInfosType.php
  src/Form/ReservationType.php
  src/Repository/ReservationRepository.php
  templates/admin/reservation/_delete_form.html.twig
  templates/admin/reservation/index.html.twig
  templates/article/index.html.twig
  templates/components/_admin_sidebar.html.twig
  templates/components/_home_services.html.twig
  templates/components/_navbar.html.twig
  templates/contact/index.html.twig
  templates/dj_dashboard/_cards_dj.html.twig
  templates/dj_dashboard/index.html.twig
  templates/login/index.html.twig
Labels: Reviewed

#382 Fix_flash_messages
  src/Controller/AdminArticleController.php
  src/Controller/AdminMusicalStyleController.php
  src/Controller/AdminPartnerController.php
  src/Controller/AdminProductionController.php
  src/Controller/AdminReservationController.php
  src/Controller/AdminTeamMemberController.php
  src/Controller/ClientController.php
  src/Controller/DjController.php
Labels: Reviewed, Fix

#384 Fix - fixtures djs
  src/DataFixtures/ArtistFixtures.php
  src/DataFixtures/UserFixtures.php
Labels: Reviewed, Fix

#386 Fix - accès espace dj
  src/Controller/DjDashboardController.php
Labels: Reviewed, Fix

#385 S04 us76 admin filter by reservation name
  assets/styles/admin.scss
  src/Controller/AdminReservationController.php
  src/Form/SearchAdminReservationType.php
  src/Repository/ReservationRepository.php
  templates/admin/reservation/index.html.twig
Labels: Reviewed, Corrections done

#391 développeur vers principal
  assets/styles/admin.scss
  assets/styles/djDashboard.scss
  config/packages/vich_uploader.yaml
  migrations/Version20220627090054.php
  public/uploads/images/documents/.gitignore
  src/Controller/AdminArticleController.php
  src/Controller/AdminMusicalStyleController.php
  src/Controller/AdminPartnerController.php
  src/Controller/AdminProductionController.php
  src/Controller/AdminReservationController.php
  src/Controller/AdminTeamMemberController.php
  src/Controller/ClientController.php
  src/Controller/DjController.php
  src/Controller/DjDashboardController.php
  src/Controller/DjProfileController.php
  src/DataFixtures/ArtistFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/.gitignore
  src/Entity/Artist.php
  src/Entity/Document.php
  src/Form/DocumentType.php
  src/Form/SearchAdminReservationType.php
  src/Repository/DocumentRepository.php
  src/Repository/ReservationRepository.php
  templates/admin/reservation/index.html.twig
  templates/components/_dj_sidebar.html.twig
  templates/dj_dashboard/profile/edit.html.twig
  templates/dj_dashboard/reservation/_accept_reservation.html.twig
  templates/dj_dashboard/reservation/show.html.twig
Labels: Reviewed

#394 Dev to main again!
  migrations/Version20220627090054.php
Labels: Reviewed

#395 Fix dj profile edit
  src/Controller/DjProfileController.php
  templates/components/_dj_sidebar.html.twig
Labels: Reviewed
